feat: add  sub-package for spore-sdk
sporeprotocol/spore-sdk pull request #109
Opened 2024-05-18 13:36 UTC by ashuralyk

# Description
since we created `DOB/0` protocol, this protocol requires developer write RUST code to generate its `pattern` for deploying Cluster, so we plan to write a codec procedure for DOB/0 right in `spore-sdk`, as it's in TypeScript which is more familiar for the most of programmers in our eco-system.

# Related Issues
- [x] #107

2024-05-18 13:53 UTC, ashuralyk commented
just ignore the failure of CI workflow, it caused by the conflict of `cross` and `cargo` version, which emits errors while compiling `spore-contracts`

2024-05-18 16:40 UTC, Hanssen0 requested changes

2024-05-18 16:40 UTC, Hanssen0 commented on packages/core/src/index.ts
Do you think this is a planned modification?

2024-05-18 16:40 UTC, Hanssen0 commented on packages/dob/src/codec/dob0/index.ts
> +export function serailizePattern(traitsBase: TraitsBase, format?: 'hex'): ArrayBuffer | string {
This interface design of multiple return types may cause some trouble with type checking. Considering this is the most essential exported function, I recommend clarifying the return type using function overloads.

2024-05-18 16:47 UTC, Hanssen0 commented
btw, please also include the `.mol` file in the source code.

2024-05-19 02:54 UTC, ashuralyk commented on packages/core/src/index.ts
sure, cobuild related interfaces should be exported

2024-05-19 03:06 UTC, Hanssen0 approved these changes
LGTM

2024-05-19 03:07 UTC, Hanssen0 approved these changes

2024-07-04 08:19 UTC, closed without merging

2024-07-04 08:19 UTC, ashuralyk commented
- [ ]